/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mx_jnilearn_MainActivity */

#ifndef _Included_com_mx_jnilearn_MainActivity
#define _Included_com_mx_jnilearn_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mx_jnilearn_MainActivity
 * Method:    getTextFromJni
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_mx_jnilearn_MainActivity_getTextFromJni
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
